version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "127.0.0.1:3308:3306"
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    ports:
      - "8083:8978"
    environment:
      CB_SERVER_PORT: 8978
      CB_SERVER_NAME: "DBeaver"
    depends_on:
      - mysql

volumes:
  mysql_data: