version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3307"
    expose:
      - 3307
    volumes:
      - mysql_data:/var/lib/mysql

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    ports:
      - "8083:8978"
    environment:
      CB_SERVER_PORT: 8978
      CB_SERVER_NAME: "DBeaver"
    depends_on:
      - mysql

volumes:
  mysql_data: