spring:
  application:
    name: spring-security-embarkx
#  security:
#    user:
#      password: 123
#      name: msanad

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test