spring:
  application:
    name: spring-security-embarkx
  security:
    user:
      password: 123
      name: msanad
  datasource:
    url: jdbc:mysql://localhost:3308/notes
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.security: TRACE
#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:mem:test