###
GET http://localhost:8080/hello
Authorization: Basic bXNhbmFkOjEyMw==

###

GET http://localhost:8080/hello
Authorization: Basic bXR6OjEyMw==

###

GET http://localhost:8080/admin
Authorization: Basic bXR6OjEyMw==

###

GET http://localhost:8080/admin
Authorization: Basic bXNhbmFkOjEyMw==


### CSRF Test Token
GET http://localhost:8080/csrf/token
Authorization: Basic bXNhbmFkOjEyMw==

### CSRF Test Attribute
GET http://localhost:8080/csrf/token1
Authorization: Basic bXNhbmFkOjEyMw==

### CSRF Test Create without token Should give 401 authorization error
POST http://localhost:8080/csrf/create
Authorization: Basic bXNhbmFkOjEyMw==
Content-Type: application/json

{
    "id": 1,
    "name": "test"
}

### CSRF Test Create without token, first run the token request and then use the token in the header
POST http://localhost:8080/csrf/create
Authorization: Basic bXNhbmFkOjEyMw==
Content-Type: application/json
X-Csrf-Token: 1e418486-5611-4ba7-860c-40fa43ba7c2c

{
  "id": 3,
  "name": "test"
}

